services:
  app:
    build: .
    container_name: support_api
    restart: always
    env_file:
      - .env.production
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mariadb:11
    container_name: support_db
    restart: always
    env_file:
      - .env.production
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: